### ISSUE TITLE
BUG  EMERGENCY

### ISSUE THREAD

**Issue by mjl9996123** [MoonRide303/Fooocus-MRE#100]
I am currently using version 2.0.19. I really like this version, it runs faster than the previous version. But I encountered a problem when generating an image: when I generated an image. When selecting quality mode, in step 40, the error prompt appears:
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "E:\Fooocus\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\Fooocus\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Fooocus\Fooocus-MRE\modules\async_worker.py", line 390, in worker
    handler(task)
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus\Fooocus-MRE\modules\async_worker.py", line 297, in handler
    imgs = pipeline.process_diffusion(task['c'], task['uc'], steps, switch, width, height, task['task_seed'],
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus\Fooocus-MRE\modules\default_pipeline.py", line 332, in process_diffusion
    sampled_latent = core.ksampler_with_refiner(
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus\Fooocus-MRE\modules\core.py", line 299, in ksampler_with_refiner
    samples = sampler.sample(noise, positive_copy, negative_copy, refiner_positive=refiner_positive_copy,
  File "E:\Fooocus\Fooocus-MRE\modules\samplers_advanced.py", line 240, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas,
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\k_diffusion\sampling.py", line 701, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\k_diffusion\sampling.py", line 615, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "E:\Fooocus\Fooocus-MRE\modules\samplers_advanced.py", line 227, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
  File "E:\Fooocus\Fooocus-MRE\modules\samplers_advanced.py", line 170, in callback
    refiner_switch()
  File "E:\Fooocus\Fooocus-MRE\modules\samplers_advanced.py", line 159, in refiner_switch
    comfy.model_management.load_model_gpu(self.refiner_model_patcher)
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 400, in load_model_gpu
    return load_models_gpu([model])
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 372, in load_models_gpu
    free_memory(total_memory_required[device] * 1.3 + extra_mem, device, models_already_loaded)
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 330, in free_memory
    m.model_unload()
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 301, in model_unload
    self.model.unpatch_model(self.model.offload_device)
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_patcher.py", line 264, in unpatch_model
    comfy.utils.set_attr(self.model, k, self.backup[k])
  File "E:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 265, in set_attr
    prev = getattr(obj, attrs[-1])
  File "E:\Fooocus\Fooocus-MRE-env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'weight'

This is not an accidental phenomenon, I have tested it many times. Subsequently, I deleted the Fooocus folder and re extracted, updated, and ran it. This problem still exists.

**Comment by MoonRide303** [comment]
@mjl9996123 It was caused by Virtual Memory system from vanilla, not compatible with current Comfy versions used in MRE - I disabled in in latest MRE today.
