### ISSUE TITLE
What is ON - image-2-image,  Revision , CN - Control-LoRA: Canny, Control-LoRA: Depth  and inpaint - error 

### ISSUE THREAD

**Issue by mirek190** [MoonRide303/Fooocus-MRE#114]
What is ON - image-2-image,  Revision , CN - Control-LoRA: Canny, Control-LoRA: Depth

..and I try to inpaint generated image - loft , right , bottom  

and gutting error :

Traceback (most recent call last):
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE\modules\async_worker.py", line 582, in worker
    handler(task)
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\DIFFUSION\Fooocus-MRE\Fooocus-MRE\modules\async_worker.py", line 206, in handler
    inpaint_mask = inpaint_input_image['mask'][:, :, 0]
TypeError: 'NoneType' object is not subscriptable

**Comment by mirek190** [comment]
Also noticed when loras are ON pictures has resolution 1024x1024 ignoring default resolution  1152×896 (9:7)

**Comment by MoonRide303** [comment]
"Enhance Image" ("Input Image" in vanilla) is new way of altering input images from vanilla - some users asked for having it in MRE, so I merged it. It should work used as standalone, but it's still pretty fresh (and big) addiction to MRE, so there might be some combination of features that don't work together. Thank you for reporting it.

**Comment by MoonRide303** [comment]
I've added automatic disabling of Image-2-Image when Enhance Image is active - those 2 functions are different way of performing img2img. While I can imagine making it work together it will be probably easier to understand for most users if they'll be working separately.

Revision and Control-LoRAs might work with Enhance Image, so I left them as they are.

When Image-2-Image mode is active then it uses aspect ratio of the original input images - this is intentional, as it allows you to process multiple input images with different dimensions, like that:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/bd996c30-56a8-4fb3-809b-38669678156f)
->
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/bd74e340-785f-457e-9cd5-8b09b32f2ad4)

**Comment by mirek190** [comment]
Nice

Thank you.!

**Comment by MoonRide303** [comment]
@mirek190 Please take a look at this new version, and let me know if it still crashes in similar scenarios. I played it for a bit and it seemed fine, but I already missed like 3 or 4 major f.ckups today, so... help with testing appreciated ;P.

**Comment by mirek190** [comment]
Just tested - works!

But I think could be a better solution just to grey image-2-image checkbox after choosing enhance image ( with small information that should appear below checkbox when is grey .

**Comment by barepixels** [comment]
Been inpainting last 6 hours.  Works great.  

Voting for this 

"Also under CN would be great to see canny or depth-generated pictures and possibility to save them and use later." 

Plus it would help to see if need to make more adjustments with the sliders

**Comment by MoonRide303** [comment]
In one of future version I will probably have to make CNs more flexible, with selectable both models and preprocessors, and - like you've said - access to preprocessor output.

One downside of that is it might become a bit confusing for end-users who didn't use CNs previously (it's not obvious how it works until you see it in action a few times).

**Comment by barepixels** [comment]
No rush because I can make depth map with A1111
