### ISSUE TITLE
increased physical memory, still does not execute successfully,

### ISSUE THREAD

**Issue by 182244013** [MoonRide303/Fooocus-MRE#129]
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.0.78.4 MRE
Inference Engine exists.
Git clone failed for Inference Engine: failed to send request: 操作超时

Total VRAM 6144 MB, total RAM 16348 MB
xformers version: 0.0.21
bin X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : native
VAE dtype: torch.float32
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Fooocus Text Processing Pipelines are retargeted to cuda:0
[Virtual Memory System] Forced = False
[Virtual Memory System] Logic target is CPU, memory = 16347.8046875
[Virtual Memory System] Activated = False
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: X:\Fooocus-MRE\Fooocus-MRE\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: X:\Fooocus-MRE\Fooocus-MRE\models\checkpoints\sd_xl_base_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
Fooocus Expansion engine loaded for cuda:0.
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Fooocus] Initializing ...
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
loading new
[Prompt Expansion] New suffix: extremely large and slender, wearing utilitarian jumpsuit, holding an assault rifle, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, cinematic lighting, art by artgerm and greg rutkowski and alphonse mucha
[Fooocus] Encoding base positive #1 ...
loading new
[Fooocus] Encoding base negative #1 ...
[Fooocus] Encoding refiner positive #1 ...
loading new
[Fooocus] Encoding refiner negative #1 ...
[Fooocus] Applying prompt strengths #1 ...
[Fooocus] Applying Revision #1 ...
[ADM] Negative ADM = True
loading new
loading in lowvram mode 3146.1895275115967
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE\modules\async_worker.py", line 603, in worker
    handler(task)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE\modules\async_worker.py", line 477, in handler
    imgs = pipeline.process_diffusion(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE\modules\default_pipeline.py", line 385, in process_diffusion
    sampled_latent = core.ksampler_with_refiner(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\Fooocus-MRE\Fooocus-MRE\modules\core.py", line 414, in ksampler_with_refiner
    comfy.model_management.load_models_gpu([model] + models, comfy.model_management.batch_area_memory(noise.shape[0] * noise.shape[2] * noise.shape[3]) + inference_memory)
  File "X:\Fooocus-MRE\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 397, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "X:\Fooocus-MRE\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 291, in model_load
    accelerate.dispatch_model(self.real_model, device_map=device_map, main_device=self.device)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\big_modeling.py", line 371, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 506, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "X:\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\accelerate\utils\modeling.py", line 292, in set_module_tensor_to_device
    new_value = old_value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 1.30 GiB already allocated; 3.67 GiB free; 1.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

![image](https://github.com/MoonRide303/Fooocus-MRE/assets/58719760/a62322b2-2832-44ca-b12a-60ce237e9726)
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/58719760/d8283a40-fd81-40db-b97b-7e16e13d1d2d)

**Comment by MoonRide303** [comment]
@182244013 Low VRAM might be the problem here - SDXL workflows barely work on computers with less than 8 GB of VRAM. Can you try setting Refiner to None in Models tab, and see if it helped?
