### ISSUE TITLE
I get an error when I launch the tool - 'Lora file not found!'

### ISSUE THREAD

**Issue by mald55** [MoonRide303/Fooocus-MRE#153]
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE\models\checkpoints\sd_xl_base_1.0_0.9vae.safetensors
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE\modules\async_worker.py", line 19, in worker
    import modules.default_pipeline as pipeline
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE\modules\default_pipeline.py", line 310, in <module>
    refresh_everything(
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE\modules\default_pipeline.py", line 305, in refresh_everything
    patch_base(loras, freeu, b1, b2, s1, s2)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "K:\AI GUI\Fooocus-MRE-v1.0.45\Fooocus-MRE\modules\default_pipeline.py", line 130, in patch_base
    assert os.path.exists(filename), 'Lora file not found!'
AssertionError: Lora file not found!

**Comment by barepixels** [comment]
you might have a typo in settings,json

**Comment by mald55** [comment]
> you might have a typo in settings,json

that was it, thank you :)
