### ISSUE TITLE
The installation of V2.0.78.5 failed many times and the following error message appeared. What is the reason?

### ISSUE THREAD

**Issue by hematrix** [MoonRide303/Fooocus-MRE#160]
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\models\checkpoints\sd_xl_base_1.0_0.9vae.safetensors
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\modules\async_worker.py", line 19, in worker
    import modules.default_pipeline as pipeline
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\modules\default_pipeline.py", line 310, in <module>
    refresh_everything(
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\modules\default_pipeline.py", line 305, in refresh_everything
    patch_base(loras, freeu, b1, b2, s1, s2)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\modules\default_pipeline.py", line 132, in patch_base
    model = core.load_sd_lora(model, filename, strength_model=weight, strength_clip=weight)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\modules\core.py", line 73, in load_sd_lora
    lora = comfy.utils.load_torch_file(lora_filename, safe_load=False)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "F:\Fooocus-MRE-v2.0.78.5\Fooocus-MRE-env\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by barepixels** [comment]
I don't have the answer but are you using Stability Matrix to install Fooocus?

**Comment by Ragamuffin20** [comment]
im having the same issue, its giving some sort of cert error
