### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by zmczmc123654** [MoonRide303/Fooocus-MRE#205]
got prompt
WARNING: '93'
!!! Exception during processing !!! Error while deserializing header: MetadataIncompleteBuffer
Traceback (most recent call last):
  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SDAI\ComfyUI-aki-v1.4\custom_nodes\comfyui_face_parsing\face_parsing_nodes.py", line 635, in main
    model = AutoModelForSemanticSegmentation.from_pretrained(face_parsing_path)
  File "D:\SDAI\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "D:\SDAI\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\modeling_utils.py", line 3994, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

Prompt executed in 0.10 seconds

**Comment by xiayela** [comment]
have you solved it?
