### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'clip'

### ISSUE THREAD

**Issue by Crazy-CYZ** [MoonRide303/Fooocus-MRE#4]
Is it necessary to opt for the SDXL Refiner model? Can it be omitted from selection?

Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Fooocus_win64_1-1-10\moonride-main\Fooocus\modules\async_worker.py", line 115, in worker
    handler(task)
  File "E:\Fooocus_win64_1-1-10\moonride-main\Fooocus\modules\async_worker.py", line 73, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, sampler_name, cfg, base_clip_skip, refiner_clip_skip, callback=callback)
  File "E:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus_win64_1-1-10\moonride-main\Fooocus\modules\default_pipeline.py", line 127, in process
    xl_refiner.clip.clip_layer(refiner_clip_skip)
AttributeError: 'NoneType' object has no attribute 'clip'

**Comment by barepixels** [comment]
I notice same error, Fooocus won't work without Refinner choosen.  But I think you need to report at https://github.com/lllyasviel/Fooocus/issues

**Comment by MoonRide303** [comment]
@xiaoyoucheng Thx for the fix, merged.

**Comment by MoonRide303** [comment]
@barepixels It's MRE-specific problem - vanilla doesn't allow to change CLIP skip, so no need to report it there.
