### ISSUE TITLE
Error after update ... 12.09.2023 - before was working  

### ISSUE THREAD

**Issue by mirek190** [MoonRide303/Fooocus-MRE#74]
Already up-to-date
Update succeeded.
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.0.0 MRE
Inference Engine exists.
Inference Engine checkout finished.
Installing requirements
Traceback (most recent call last):
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE\entry_with_update.py", line 46, in <module>
    from launch import *
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE\launch.py", line 137, in <module>
    from webui import *
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE\webui.py", line 1, in <module>
    import gradio as gr
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\DIFFUSION\Fooocus-MRE-v1.0.40\Fooocus-MRE-env\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .

**Comment by MoonRide303** [comment]
@mirek190 Please try downloading newer full package (the big one, with env), and let me know if it helped.

**Comment by mirek190** [comment]
After downloading full package works ..... Thanks.

But updating processes from 1.x to 2.x broke Fooocus-MRE.

**Comment by MoonRide303** [comment]
@mirek190 Okay, thanks for the information. That might be related to additional requirements that were added around v1.0.45, so it could be transition from v1.0.40 to v1.0.45 that caused the problems (FastAPI was added in v1.0.43, and I see it in the stacktrace). I will have to look into this, why it didn't work.
