### ISSUE TITLE
Bug in 2.0.19?

### ISSUE THREAD

**Issue by Jisevind** [MoonRide303/Fooocus-MRE#94]
Hi,

I updated to 2.0.19 and now I'm getting some "Permission Denied". Nothing has changed in my folder structure.

Already up-to-date
Update succeeded.
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.0.19 MRE
Inference Engine exists.
Inference Engine checkout finished.
Total VRAM 8192 MB, total RAM 65375 MB
xformers version: 0.0.21
bin D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 2070 Super : native
VAE dtype: torch.float32
Using xformers cross attention
[Virtual Memory System] Logic target is CPU, memory = 65374.65234375
[Virtual Memory System] Activated = False
Fooocus Text Processing Pipelines are retargeted to cuda:0
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\modules\async_worker.py", line 40, in worker
    import modules.default_pipeline as pipeline
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\modules\default_pipeline.py", line 269, in <module>
    refresh_everything(
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\modules\default_pipeline.py", line 256, in refresh_everything
    refresh_refiner_model(refiner_model_name)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\modules\default_pipeline.py", line 85, in refresh_refiner_model
    xl_refiner = core.load_model(filename)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\modules\core.py", line 60, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=embeddings_path)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 396, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 20, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\AI-Apps\Fooocus-MRE\Fooocus-MRE-env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'D:\\AI-Apps\\Fooocus-MRE\\Fooocus-MRE\\models\\checkpoints'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by MoonRide303** [comment]
@Jisevind Please check your outputs path - in v2.0.19 fix was added for log links not working with custom outputs path.

**Comment by Jisevind** [comment]
The problem seems to be with the settings.json file. I have these lines and it's been working so far.

"base_model": "protovisionXLHighFidelity3D_beta0520Bakedvae.safetensors",
"refiner_model": "",

Now it does not work unless I specify a refiner

"base_model": "protovisionXLHighFidelity3D_beta0520Bakedvae.safetensors",
"refiner_model": "sd_xl_refiner_1.0_0.9vae.safetensors",

Removing the line did not work either, then it defaults to "sd_xl_refiner_1.0_0.9vae.safetensors"

**Comment by MoonRide303** [comment]
@Jisevind If you want to disable refiner model you should set it to "None" (as in `settings-no-refiner.json` file).

**Comment by Jisevind** [comment]
Completely missed settings-no-refiner.json, thank you!
